const {inr,inrNum,BY_ID,PRESETS,computeQuote}=require('./extract-engine.js');
let pass=0,fail=0;
function eq(l,g,w){const ok=String(g)===String(w);ok?pass++:fail++;console.log(`${ok?'  PASS':'  FAIL'}  ${l}  (got=${g} want=${w})`);}
const lp=n=>PRESETS[n].map(([id,q])=>({...BY_ID[id],qty:q}));
const S=o=>Object.assign({lines:[],gstMode:'extra',gstPct:18,discPct:0,months:12},o);
console.log('\n=== 1. Indian digit grouping ===');
eq('123456 -> 1,23,456',inrNum(123456),'1,23,456');
eq('4700000 -> 47,00,000',inrNum(4700000),'47,00,000');
eq('40000',inrNum(40000),'40,000'); eq('999',inrNum(999),'999');
console.log('\n=== 2. Real Estate Campaign = REAL quote Rs 40,000 ===');
let r=computeQuote(S({lines:lp('Real Estate Campaign')}));
eq('one-time gross',r.buckets.one_time.gross,40000);
eq('GST 18%',Math.round(r.buckets.one_time.gst),7200);
eq('total w/GST',Math.round(r.buckets.one_time.total),47200);
eq('nothing leaked to monthly',r.buckets.monthly.gross,0);
console.log('\n=== 3. Website Pkg1 = REAL quote Rs 36,000 ===');
r=computeQuote(S({lines:lp('Website Package 1'),gstMode:'none'}));
eq('design one-time',r.buckets.one_time.gross,26010);
eq('domain+host yearly',r.buckets.yearly.gross,9990);
eq('TCV yr1 = 36,000',Math.round(r.tcv.total),36000);
console.log('\n=== 4. Pkg2 / Pkg3 parity ===');
eq('Pkg2 = 46,000',Math.round(computeQuote(S({lines:lp('Website Package 2'),gstMode:'none'})).tcv.total),46000);
eq('Pkg3 = 56,000',Math.round(computeQuote(S({lines:lp('Website Package 3'),gstMode:'none'})).tcv.total),56000);
console.log('\n=== 5. Quantity scaling ===');
eq('8 creatives = 6,400',computeQuote(S({lines:[{...BY_ID.creatives,qty:8}],gstMode:'none'})).buckets.monthly.gross,6400);
eq('1 creative = 800',computeQuote(S({lines:[{...BY_ID.creatives,qty:1}],gstMode:'none'})).buckets.monthly.gross,800);
eq('14 days FB = 16,800',computeQuote(S({lines:[{...BY_ID.fbCamp,qty:14}],gstMode:'none'})).buckets.one_time.gross,16800);
console.log('\n=== 5b. Retainer vs campaign creatives are distinct ===');
eq('retainer is monthly',BY_ID.creatives.b,'monthly');
eq('campaign is one_time',BY_ID.creativesCamp.b,'one_time');
eq('same rate',BY_ID.creatives.rate,BY_ID.creativesCamp.rate);
console.log('\n=== 6. Buckets never wrongly summed ===');
r=computeQuote(S({lines:[{...BY_ID.smSetup,qty:1},{...BY_ID.creatives,qty:4},{...BY_ID.domain,qty:1}],gstMode:'none',months:6}));
eq('one_time',r.buckets.one_time.gross,6000);
eq('monthly',r.buckets.monthly.gross,3200);
eq('yearly',r.buckets.yearly.gross,1490);
eq('TCV 6mo = 26,690',Math.round(r.tcv.total),26690);
console.log('\n=== 7. Discount ===');
r=computeQuote(S({lines:lp('Real Estate Campaign'),discPct:10,gstMode:'none'}));
eq('10% off -> net 36,000',Math.round(r.buckets.one_time.net),36000);
eq('discount = 4,000',Math.round(r.buckets.one_time.disc),4000);
console.log('\n=== 8. GST-inclusive back-calculation ===');
r=computeQuote(S({lines:[{n:'x',stdQty:1,qty:1,rate:47200,b:'one_time'}],gstMode:'incl'}));
eq('base 40,000',Math.round(r.buckets.one_time.base),40000);
eq('gst 7,200',Math.round(r.buckets.one_time.gst),7200);
eq('total 47,200',Math.round(r.buckets.one_time.total),47200);
console.log('\n=== 9. Edge cases ===');
eq('empty total 0',computeQuote(S({})).tcv.total,0);
eq('qty0 excluded',computeQuote(S({lines:[{...BY_ID.creatives,qty:0}],gstMode:'none'})).buckets.monthly.gross,0);
eq('discount clamp',Math.round(computeQuote(S({lines:lp('Real Estate Campaign'),discPct:150,gstMode:'none'})).buckets.one_time.net),0);
eq('months clamp',computeQuote(S({lines:lp('Real Estate Campaign'),months:0})).termMonths,1);
eq('negative qty ignored',computeQuote(S({lines:[{...BY_ID.creatives,qty:-5}],gstMode:'none'})).buckets.monthly.gross,0);
console.log('\n=== 10. Currency symbol ===');
eq('inr(47200)',inr(47200),'\u20B947,200');
console.log(`\n────────────────────────\n  ${pass} passed, ${fail} failed\n────────────────────────`);
process.exit(fail?1:0);
